runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
  login: required
  secure: always
# [END handlers]

libraries:
- name: ssl
  version: latest

 env_variables:
     EMAIL_API_KEY: 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
